/* The following code was generated by JFlex 1.6.1 */

package LexicoDosLang;
import java_cup.runtime.*;
import SintacticoDosLang.sym;
import Excepciones.Excepcion;
import Excepciones.Excepcion.TIPOERROR;
import doslang.DosLang;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Lexico.jflex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHARACTER = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\66\1\67\1\1\22\0\1\3\1\0\1\64"+
    "\2\0\1\61\1\0\1\65\1\7\1\11\1\10\1\51\1\57\1\52"+
    "\1\5\1\53\1\72\11\4\1\47\1\54\1\62\1\50\1\63\1\71"+
    "\1\0\1\23\1\27\1\25\1\32\1\20\1\37\1\21\1\26\1\15"+
    "\1\6\1\45\1\24\1\41\1\16\1\30\1\36\1\6\1\22\1\34"+
    "\1\17\1\42\1\43\1\31\1\46\1\35\1\40\1\55\1\70\1\56"+
    "\1\60\1\6\1\0\1\23\1\27\1\25\1\32\1\20\1\37\1\21"+
    "\1\26\1\15\1\6\1\45\1\24\1\41\1\16\1\30\1\36\1\6"+
    "\1\22\1\34\1\17\1\42\1\43\1\31\1\46\1\35\1\40\1\12"+
    "\1\0\1\13\7\0\1\66\53\0\1\6\21\0\1\6\154\0\2\14"+
    "\115\0\1\33\u1e98\0\1\6\17\0\1\66\1\66\u0100\0\1\44\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\2\1\13\5\1\1\6\5\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\2\31\1\32\1\33"+
    "\1\34\1\35\2\36\1\37\1\40\1\0\1\41\2\0"+
    "\1\42\1\0\1\43\1\5\1\43\1\0\5\5\1\44"+
    "\15\5\1\45\1\46\1\0\4\5\1\47\2\0\11\5"+
    "\1\0\2\5\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\1\64\1\65"+
    "\1\66\1\67\1\70\1\71\1\72\1\73\2\0\1\5"+
    "\2\74\1\5\1\75\1\76\3\5\1\77\1\0\1\5"+
    "\1\0\4\5\1\100\1\5\1\0\6\5\1\0\1\5"+
    "\1\0\1\5\1\0\3\5\2\0\5\5\1\101\3\5"+
    "\1\0\1\5\1\102\1\0\1\5\1\103\1\104\1\105"+
    "\1\106\2\107\2\110\1\111\1\112\3\5\2\113\1\114"+
    "\1\5\1\0\1\5\1\0\3\5\2\115\1\0\1\5"+
    "\1\0\1\5\1\116\1\5\2\0\4\5\1\117\1\0"+
    "\3\5\1\0\1\5\2\120\1\0\3\5\1\121\1\0"+
    "\1\5\2\122\2\123\2\124\1\5\2\125\2\126\1\5"+
    "\2\0\4\5\2\127\2\5\2\130\1\0\1\5\1\131"+
    "\1\132\1\0\2\5\1\0\1\5\1\133\1\134\1\135"+
    "\1\134\1\135\2\5\1\0\1\5\1\136\2\137\1\0"+
    "\1\5\1\140\2\141\1\142\1\5\1\0\1\5\2\143"+
    "\1\5\2\144\1\145";

  private static int [] zzUnpackAction() {
    int [] result = new int[294];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\261\0\u0127\0\u0162"+
    "\0\u019d\0\u01d8\0\261\0\261\0\u0213\0\u024e\0\u0289\0\u02c4"+
    "\0\u02ff\0\u033a\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c"+
    "\0\u04d7\0\u0512\0\u054d\0\u0588\0\u05c3\0\u05fe\0\u0639\0\u0674"+
    "\0\u06af\0\261\0\261\0\261\0\261\0\261\0\261\0\261"+
    "\0\261\0\261\0\261\0\u06ea\0\u0725\0\261\0\261\0\261"+
    "\0\u0760\0\261\0\261\0\u079b\0\261\0\261\0\u07d6\0\261"+
    "\0\261\0\u0811\0\u084c\0\u0887\0\u08c2\0\u0213\0\261\0\u08fd"+
    "\0\261\0\u0938\0\u019d\0\u0973\0\u09ae\0\u09e9\0\u0a24\0\u0a5f"+
    "\0\u0a9a\0\u019d\0\u0ad5\0\u0b10\0\u0b4b\0\u0b86\0\u0bc1\0\u0bfc"+
    "\0\u0c37\0\u0c72\0\u0cad\0\u0ce8\0\u0d23\0\u0d5e\0\u0d99\0\u019d"+
    "\0\u019d\0\u0dd4\0\u0e0f\0\u0e4a\0\u0e85\0\u0ec0\0\u0efb\0\u0f36"+
    "\0\u0f71\0\u0fac\0\u0fe7\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e"+
    "\0\u1149\0\u1184\0\u11bf\0\u11fa\0\u1235\0\261\0\261\0\261"+
    "\0\261\0\261\0\261\0\261\0\261\0\261\0\261\0\261"+
    "\0\261\0\261\0\261\0\261\0\261\0\261\0\261\0\u084c"+
    "\0\261\0\u1270\0\u12ab\0\u12e6\0\261\0\u019d\0\u1321\0\u019d"+
    "\0\u019d\0\u135c\0\u1397\0\u13d2\0\u019d\0\u140d\0\u1448\0\u1483"+
    "\0\u14be\0\u14f9\0\u1534\0\u156f\0\u019d\0\u15aa\0\u15e5\0\u1620"+
    "\0\u165b\0\u1696\0\u16d1\0\u170c\0\u1747\0\u1782\0\u17bd\0\u17f8"+
    "\0\u1833\0\u186e\0\u18a9\0\u18e4\0\u191f\0\u195a\0\u1995\0\u19d0"+
    "\0\u1a0b\0\u1a46\0\u1a81\0\u1abc\0\u019d\0\u1af7\0\u1b32\0\u1b6d"+
    "\0\u1ba8\0\u1be3\0\u019d\0\u1c1e\0\u1c59\0\u019d\0\u019d\0\u019d"+
    "\0\u019d\0\261\0\u019d\0\261\0\u019d\0\u019d\0\u019d\0\u1c94"+
    "\0\u1ccf\0\u1d0a\0\261\0\u019d\0\u019d\0\u1d45\0\u1d80\0\u1dbb"+
    "\0\u1df6\0\u1e31\0\u1e6c\0\u1ea7\0\261\0\u019d\0\u1ee2\0\u1f1d"+
    "\0\u1f58\0\u1f93\0\u019d\0\u1fce\0\u2009\0\u2044\0\u207f\0\u20ba"+
    "\0\u20f5\0\u2130\0\u019d\0\u216b\0\u21a6\0\u21e1\0\u221c\0\u2257"+
    "\0\u2292\0\261\0\u019d\0\u22cd\0\u2308\0\u2343\0\u237e\0\u019d"+
    "\0\u23b9\0\u23f4\0\261\0\u019d\0\261\0\u019d\0\261\0\u019d"+
    "\0\u242f\0\u246a\0\u24a5\0\261\0\u019d\0\u24e0\0\u251b\0\u2556"+
    "\0\u2591\0\u25cc\0\u2607\0\u2642\0\261\0\u019d\0\u267d\0\u26b8"+
    "\0\261\0\u019d\0\u26f3\0\u272e\0\u019d\0\u019d\0\u2769\0\u27a4"+
    "\0\u27df\0\u281a\0\u2855\0\u019d\0\261\0\261\0\u019d\0\u019d"+
    "\0\u2890\0\u28cb\0\u2906\0\u2941\0\u019d\0\261\0\u019d\0\u297c"+
    "\0\u29b7\0\u019d\0\261\0\u019d\0\u019d\0\u29f2\0\u2a2d\0\u2a68"+
    "\0\261\0\u019d\0\u2aa3\0\261\0\u019d\0\u019d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[294];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\4\1\16\1\17\1\20\1\21\1\22"+
    "\1\11\1\23\1\24\1\11\1\25\1\11\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\11\1\34\1\35\1\11"+
    "\1\36\1\37\1\40\1\4\2\11\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\0\1\6\2\4\1\7"+
    "\1\60\1\61\1\62\61\60\1\63\1\60\2\0\1\64"+
    "\1\65\1\60\1\66\1\67\1\70\62\66\1\71\2\0"+
    "\1\72\2\66\75\0\1\6\74\0\1\7\1\73\64\0"+
    "\1\7\5\0\1\74\71\0\1\11\1\0\1\11\6\0"+
    "\16\11\1\0\10\11\1\0\2\11\23\0\1\11\10\0"+
    "\1\75\62\0\13\76\1\77\57\76\16\0\1\100\20\0"+
    "\1\101\37\0\1\11\1\0\1\11\6\0\1\11\1\102"+
    "\14\11\1\0\3\11\1\103\4\11\1\0\2\11\23\0"+
    "\1\11\4\0\1\11\1\0\1\11\5\0\1\104\1\105"+
    "\5\11\1\106\4\11\1\107\2\11\1\0\10\11\1\0"+
    "\2\11\23\0\1\11\4\0\1\11\1\0\1\11\6\0"+
    "\5\11\1\110\3\11\1\111\1\11\1\112\2\11\1\0"+
    "\1\11\1\113\6\11\1\0\2\11\23\0\1\11\4\0"+
    "\1\11\1\0\1\11\6\0\1\11\1\114\5\11\1\115"+
    "\6\11\1\0\10\11\1\0\1\11\1\116\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\3\11\1\117\12\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\1\11\1\120\3\11\1\121\10\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\6\11\1\122\2\11\1\123\1\11"+
    "\1\124\2\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\3\11\1\125\1\11"+
    "\1\126\5\11\1\127\2\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\6\0\5\11"+
    "\1\130\10\11\1\0\3\11\1\131\4\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\5\0\1\132"+
    "\1\133\4\11\1\134\3\11\1\135\1\11\1\136\2\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\13\11\1\137\2\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\14\0\2\140\1\0\1\141"+
    "\57\0\1\11\1\0\1\11\5\0\1\140\1\142\1\11"+
    "\1\143\13\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\5\11\1\144\10\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\5\11\1\145\1\146\4\11\1\147"+
    "\2\11\1\0\6\11\1\150\1\11\1\0\2\11\23\0"+
    "\1\11\4\0\1\11\1\0\1\11\6\0\6\11\1\151"+
    "\7\11\1\0\10\11\1\0\2\11\23\0\1\11\4\0"+
    "\1\11\1\0\1\11\6\0\1\11\1\152\14\11\1\153"+
    "\1\154\7\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\6\11\1\155\7\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\50\0\1\156\72\0\1\157"+
    "\12\0\1\160\57\0\1\161\24\0\1\62\106\0\1\162"+
    "\1\163\2\0\1\164\1\165\3\0\1\166\7\0\1\167"+
    "\3\0\1\170\20\0\1\171\1\172\4\0\1\173\2\0"+
    "\1\70\106\0\1\174\1\175\2\0\1\176\41\0\1\177"+
    "\12\0\1\200\65\0\1\200\5\0\1\201\65\0\10\75"+
    "\1\202\62\75\17\0\1\203\57\0\1\11\1\0\1\11"+
    "\6\0\2\11\1\204\13\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\24\0\1\205\52\0\1\11\1\0\1\11"+
    "\6\0\7\11\1\206\6\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\6\0\1\11"+
    "\1\207\14\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\2\11\1\210\2\11"+
    "\1\211\10\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\16\11\1\0\6\11"+
    "\1\212\1\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\3\11\1\213\12\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\16\11\1\0\2\11\1\214\5\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\6\0\15\11"+
    "\1\215\1\0\10\11\1\0\2\11\23\0\1\11\4\0"+
    "\1\11\1\0\1\11\6\0\16\11\1\216\1\217\7\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\5\0\1\220\1\221\15\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\6\0\6\11"+
    "\1\222\1\11\1\223\5\11\1\0\2\11\1\224\5\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\15\11\1\225\1\0\10\11\1\0\2\11\23\0"+
    "\1\11\4\0\1\11\1\0\1\11\6\0\5\11\1\226"+
    "\10\11\1\0\10\11\1\0\2\11\23\0\1\11\4\0"+
    "\1\11\1\0\1\11\6\0\16\11\1\227\1\230\7\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\6\11\1\231\7\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\6\0\1\11"+
    "\1\232\14\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\4\11\1\233\11\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\3\11\1\234\12\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\13\11\1\235\2\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\17\0\1\236\57\0\1\11\1\0\1\11"+
    "\6\0\2\11\1\237\13\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\5\0\1\240"+
    "\1\241\15\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\5\0\1\242\1\243\15\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\5\11\1\244\10\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\14\11\1\245\1\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\40\0\1\246\54\0\1\247\54\0\1\11"+
    "\1\0\1\11\6\0\16\11\1\0\4\11\1\250\3\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\5\11\1\251\10\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\6\0\13\11"+
    "\1\252\2\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\3\11\1\253\12\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\7\11\1\254\6\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\5\11\1\255\10\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\6\0\1\11"+
    "\1\256\14\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\7\11\1\257\6\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\2\11\1\260\13\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\20\0\1\261\56\0\1\11"+
    "\1\0\1\11\6\0\3\11\1\262\12\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\5\11\1\263\10\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\10\75\1\202\1\77\61\75\20\0\1\264"+
    "\56\0\1\11\1\0\1\11\6\0\3\11\1\265\12\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\15\11\1\266\1\0\10\11\1\0"+
    "\2\11\23\0\1\11\4\0\1\11\1\0\1\11\6\0"+
    "\3\11\1\267\12\11\1\0\10\11\1\0\2\11\23\0"+
    "\1\11\4\0\1\11\1\0\1\11\6\0\1\11\1\270"+
    "\14\11\1\0\10\11\1\0\2\11\23\0\1\11\4\0"+
    "\1\11\1\0\1\11\6\0\3\11\1\271\12\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\20\0\1\272\56\0"+
    "\1\11\1\0\1\11\6\0\3\11\1\273\12\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\17\0\1\274\57\0"+
    "\1\11\1\0\1\11\6\0\2\11\1\275\13\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\4\0\1\11\1\0"+
    "\1\11\6\0\7\11\1\276\5\11\1\277\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\13\11\1\300\2\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\6\0\3\11"+
    "\1\301\12\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\6\11\1\302\7\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\20\0\1\303"+
    "\56\0\1\11\1\0\1\11\6\0\3\11\1\304\12\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\5\11\1\305\10\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\2\11\1\306\13\11\1\307\1\310\7\11\1\0"+
    "\2\11\23\0\1\11\4\0\1\11\1\0\1\11\5\0"+
    "\1\311\1\312\15\11\1\0\10\11\1\0\2\11\23\0"+
    "\1\11\4\0\1\11\1\0\1\11\6\0\6\11\1\313"+
    "\7\11\1\0\10\11\1\0\2\11\23\0\1\11\4\0"+
    "\1\11\1\0\1\11\6\0\7\11\1\314\6\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\26\0\1\315\50\0"+
    "\1\11\1\0\1\11\6\0\11\11\1\316\4\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\17\0\1\317\57\0"+
    "\1\11\1\0\1\11\6\0\2\11\1\320\13\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\24\0\1\321\52\0"+
    "\1\11\1\0\1\11\6\0\7\11\1\322\6\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\4\0\1\11\1\0"+
    "\1\11\6\0\15\11\1\323\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\6\0\1\11"+
    "\1\324\14\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\20\0\1\325\66\0\2\326\61\0\1\11\1\0\1\11"+
    "\6\0\3\11\1\327\12\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\5\0\1\326"+
    "\1\330\15\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\4\11\1\331\3\11"+
    "\1\332\5\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\3\11\1\333\12\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\16\11\1\334\1\335\7\11\1\0"+
    "\2\11\23\0\1\11\4\0\1\11\1\0\1\11\6\0"+
    "\10\11\1\336\5\11\1\0\10\11\1\0\2\11\23\0"+
    "\1\11\4\0\1\11\1\0\1\11\6\0\7\11\1\337"+
    "\6\11\1\0\10\11\1\0\2\11\23\0\1\11\4\0"+
    "\1\11\1\0\1\11\5\0\1\340\1\341\15\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\33\0\2\342\42\0"+
    "\1\11\1\0\1\11\6\0\16\11\1\342\1\343\7\11"+
    "\1\0\2\11\23\0\1\11\21\0\1\344\55\0\1\11"+
    "\1\0\1\11\6\0\4\11\1\345\11\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\5\11\1\346\10\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\6\0\6\11"+
    "\1\347\7\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\16\11\1\0\1\11"+
    "\1\350\6\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\5\0\1\351\1\352\15\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\17\0\1\353\57\0\1\11"+
    "\1\0\1\11\6\0\2\11\1\354\13\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\16\0\1\355\60\0\1\11"+
    "\1\0\1\11\6\0\1\11\1\356\14\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\16\11\1\0\10\11\1\357\1\360\1\11\23\0"+
    "\1\11\4\0\1\11\1\0\1\11\6\0\3\11\1\361"+
    "\12\11\1\0\10\11\1\0\2\11\23\0\1\11\20\0"+
    "\1\362\56\0\1\11\1\0\1\11\6\0\3\11\1\363"+
    "\12\11\1\0\10\11\1\0\2\11\23\0\1\11\20\0"+
    "\1\364\56\0\1\11\1\0\1\11\6\0\3\11\1\365"+
    "\12\11\1\0\10\11\1\0\2\11\23\0\1\11\4\0"+
    "\1\11\1\0\1\11\6\0\2\11\1\366\13\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\30\0\1\367\60\0"+
    "\1\370\60\0\1\11\1\0\1\11\6\0\13\11\1\371"+
    "\2\11\1\0\10\11\1\0\2\11\23\0\1\11\4\0"+
    "\1\11\1\0\1\11\6\0\1\11\1\372\14\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\4\0\1\11\1\0"+
    "\1\11\6\0\5\11\1\373\10\11\1\0\10\11\1\0"+
    "\2\11\23\0\1\11\4\0\1\11\1\0\1\11\6\0"+
    "\3\11\1\374\12\11\1\0\10\11\1\0\2\11\23\0"+
    "\1\11\20\0\1\375\56\0\1\11\1\0\1\11\6\0"+
    "\3\11\1\376\12\11\1\0\10\11\1\0\2\11\23\0"+
    "\1\11\4\0\1\11\1\0\1\11\6\0\2\11\1\377"+
    "\13\11\1\0\10\11\1\0\2\11\23\0\1\11\4\0"+
    "\1\11\1\0\1\11\6\0\13\11\1\u0100\2\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\24\0\1\u0101\52\0"+
    "\1\11\1\0\1\11\6\0\7\11\1\u0102\6\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\20\0\1\u0103\56\0"+
    "\1\11\1\0\1\11\6\0\3\11\1\u0104\12\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\4\0\1\11\1\0"+
    "\1\11\6\0\15\11\1\u0105\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\6\0\2\11"+
    "\1\u0106\13\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\16\0\1\u0107\60\0\1\11\1\0\1\11\6\0\1\11"+
    "\1\u0108\14\11\1\0\10\11\1\0\2\11\23\0\1\11"+
    "\4\0\1\11\1\0\1\11\6\0\6\11\1\u0109\7\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\24\0\1\u010a"+
    "\52\0\1\11\1\0\1\11\6\0\7\11\1\u010b\6\11"+
    "\1\0\10\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\13\11\1\u010c\2\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\37\0\1\u010d\54\0\1\u010e"+
    "\55\0\1\11\1\0\1\11\6\0\16\11\1\0\3\11"+
    "\1\u010f\4\11\1\0\2\11\23\0\1\11\4\0\1\11"+
    "\1\0\1\11\6\0\4\11\1\u0110\11\11\1\0\10\11"+
    "\1\0\2\11\23\0\1\11\4\0\1\11\1\0\1\11"+
    "\6\0\6\11\1\u0111\7\11\1\0\10\11\1\0\2\11"+
    "\23\0\1\11\4\0\1\11\1\0\1\11\6\0\15\11"+
    "\1\u0112\1\0\10\11\1\0\2\11\23\0\1\11\4\0"+
    "\1\11\1\0\1\11\5\0\1\u0113\1\u0114\15\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\4\0\1\11\1\0"+
    "\1\11\6\0\10\11\1\u0115\5\11\1\0\10\11\1\0"+
    "\2\11\23\0\1\11\22\0\1\u0116\54\0\1\11\1\0"+
    "\1\11\6\0\5\11\1\u0117\10\11\1\0\10\11\1\0"+
    "\2\11\23\0\1\11\42\0\1\u0118\34\0\1\11\1\0"+
    "\1\11\6\0\16\11\1\0\6\11\1\u0119\1\11\1\0"+
    "\2\11\23\0\1\11\4\0\1\11\1\0\1\11\6\0"+
    "\1\11\1\u011a\14\11\1\0\10\11\1\0\2\11\23\0"+
    "\1\11\16\0\1\u011b\60\0\1\11\1\0\1\11\6\0"+
    "\1\11\1\u011c\14\11\1\0\10\11\1\0\2\11\23\0"+
    "\1\11\4\0\1\11\1\0\1\11\6\0\16\11\1\0"+
    "\5\11\1\u011d\2\11\1\0\2\11\23\0\1\11\4\0"+
    "\1\11\1\0\1\11\6\0\16\11\1\0\6\11\1\u011e"+
    "\1\11\1\0\2\11\23\0\1\11\30\0\1\u011f\46\0"+
    "\1\11\1\0\1\11\6\0\13\11\1\u0120\2\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\20\0\1\u0121\56\0"+
    "\1\11\1\0\1\11\6\0\3\11\1\u0122\12\11\1\0"+
    "\10\11\1\0\2\11\23\0\1\11\4\0\1\11\1\0"+
    "\1\11\6\0\5\11\1\u0123\10\11\1\0\10\11\1\0"+
    "\2\11\23\0\1\11\16\0\1\u0124\60\0\1\11\1\0"+
    "\1\11\6\0\1\11\1\u0125\14\11\1\0\10\11\1\0"+
    "\2\11\23\0\1\11\4\0\1\11\1\0\1\11\6\0"+
    "\3\11\1\u0126\12\11\1\0\10\11\1\0\2\11\23\0"+
    "\1\11";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10974];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\4\1\2\11\25\1\12\11"+
    "\2\1\3\11\1\1\2\11\1\1\2\11\1\1\2\11"+
    "\1\1\1\0\1\1\2\0\1\11\1\0\1\11\2\1"+
    "\1\0\25\1\1\0\5\1\2\0\11\1\1\0\2\1"+
    "\22\11\1\1\1\11\2\0\1\1\1\11\10\1\1\0"+
    "\1\1\1\0\6\1\1\0\6\1\1\0\1\1\1\0"+
    "\1\1\1\0\3\1\2\0\11\1\1\0\2\1\1\0"+
    "\5\1\1\11\1\1\1\11\6\1\1\11\3\1\1\0"+
    "\1\1\1\0\3\1\1\11\1\1\1\0\1\1\1\0"+
    "\3\1\2\0\5\1\1\0\3\1\1\0\1\1\1\11"+
    "\1\1\1\0\4\1\1\0\1\1\1\11\1\1\1\11"+
    "\1\1\1\11\4\1\1\11\2\1\2\0\4\1\1\11"+
    "\3\1\1\11\1\1\1\0\3\1\1\0\2\1\1\0"+
    "\2\1\2\11\4\1\1\0\2\1\1\11\1\1\1\0"+
    "\2\1\1\11\3\1\1\0\1\1\1\11\2\1\1\11"+
    "\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[294];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }
    StringBuilder NuevoString = new StringBuilder();
    char NuevoChar;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 252) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { yybegin(YYINITIAL); 
                          DosLang.errores.add(new Excepcion(TIPOERROR.LEXICO, 
                                                        "El caracter '"+yytext()+"' no pertenece al lenguaje", 
                                                        yyline, 
                                                        yycolumn));
            }
          case 102: break;
          case 2: 
            { 
            }
          case 103: break;
          case 3: 
            { return symbol(sym.numero, yytext().toLowerCase());
            }
          case 104: break;
          case 4: 
            { return symbol(sym.punto, ".");
            }
          case 105: break;
          case 5: 
            { return symbol(sym.identificador, yytext().toLowerCase());
            }
          case 106: break;
          case 6: 
            { return symbol(sym.parenI, "(");
            }
          case 107: break;
          case 7: 
            { return symbol(sym.por, "*");
            }
          case 108: break;
          case 8: 
            { return symbol(sym.parenD, ")");
            }
          case 109: break;
          case 9: 
            { return symbol(sym.dosPuntos, ":");
            }
          case 110: break;
          case 10: 
            { return symbol(sym.igualacion, "=");
            }
          case 111: break;
          case 11: 
            { return symbol(sym.mas, "+");
            }
          case 112: break;
          case 12: 
            { return symbol(sym.menos, "-");
            }
          case 113: break;
          case 13: 
            { return symbol(sym.division, "/");
            }
          case 114: break;
          case 14: 
            { return symbol(sym.pComa, ";");
            }
          case 115: break;
          case 15: 
            { return symbol(sym.corI, "[");
            }
          case 116: break;
          case 16: 
            { return symbol(sym.corD, "]");
            }
          case 117: break;
          case 17: 
            { return symbol(sym.coma, ",");
            }
          case 118: break;
          case 18: 
            { return symbol(sym.potencia, "^");
            }
          case 119: break;
          case 19: 
            { return symbol(sym.modulo, "%");
            }
          case 120: break;
          case 20: 
            { return symbol(sym.menorque, "<");
            }
          case 121: break;
          case 21: 
            { return symbol(sym.mayorque, ">");
            }
          case 122: break;
          case 22: 
            { yybegin(STRING); NuevoString.setLength(0);
            }
          case 123: break;
          case 23: 
            { yybegin(CHARACTER); NuevoChar = ' ';
            }
          case 124: break;
          case 24: 
            { NuevoString.append(yytext());
            }
          case 125: break;
          case 25: 
            { yybegin(YYINITIAL);
                                   DosLang.errores.add(new Excepcion(TIPOERROR.LEXICO, 
                                                                 "String sin finalizar", 
                                                                 yyline, 
                                                                 yycolumn));
            }
          case 126: break;
          case 26: 
            { yybegin(YYINITIAL); return symbol(sym.cadena, NuevoString.toString());
            }
          case 127: break;
          case 27: 
            { NuevoString.append('\\');
            }
          case 128: break;
          case 28: 
            { NuevoString.append('?');
            }
          case 129: break;
          case 29: 
            { NuevoChar = yytext().charAt(0);
            }
          case 130: break;
          case 30: 
            { yybegin(YYINITIAL);
                                   DosLang.errores.add(new Excepcion(TIPOERROR.LEXICO, 
                                                                 "Char sin finalizar", 
                                                                 yyline, 
                                                                 yycolumn));
            }
          case 131: break;
          case 31: 
            { yybegin(YYINITIAL); 
                                   return symbol(sym.caracter, NuevoChar);
            }
          case 132: break;
          case 32: 
            { NuevoChar = '\\';
            }
          case 133: break;
          case 33: 
            { return symbol(sym.dosP, "..");
            }
          case 134: break;
          case 34: 
            { /* ignore */
            }
          case 135: break;
          case 35: 
            { return symbol(sym.si, yytext().toLowerCase());
            }
          case 136: break;
          case 36: 
            { return symbol(sym.to, yytext().toLowerCase());
            }
          case 137: break;
          case 37: 
            { return symbol(sym.or, yytext().toLowerCase());
            }
          case 138: break;
          case 38: 
            { return symbol(sym.of, yytext().toLowerCase());
            }
          case 139: break;
          case 39: 
            { return symbol(sym.hacer, yytext().toLowerCase());
            }
          case 140: break;
          case 40: 
            { return symbol(sym.igual, ":=");
            }
          case 141: break;
          case 41: 
            { return symbol(sym.menorigual, "<=");
            }
          case 142: break;
          case 42: 
            { return symbol(sym.diferente, "<>");
            }
          case 143: break;
          case 43: 
            { return symbol(sym.mayorigual, ">=");
            }
          case 144: break;
          case 44: 
            { NuevoString.append('\n');
            }
          case 145: break;
          case 45: 
            { NuevoString.append('\t');
            }
          case 146: break;
          case 46: 
            { NuevoString.append('\r');
            }
          case 147: break;
          case 47: 
            { NuevoString.append('a');
            }
          case 148: break;
          case 48: 
            { NuevoString.append('\b');
            }
          case 149: break;
          case 49: 
            { NuevoString.append('\f');
            }
          case 150: break;
          case 50: 
            { NuevoString.append('v');
            }
          case 151: break;
          case 51: 
            { NuevoString.append('\"');
            }
          case 152: break;
          case 52: 
            { NuevoString.append('\'');
            }
          case 153: break;
          case 53: 
            { NuevoString.append('\0');
            }
          case 154: break;
          case 54: 
            { NuevoChar = '\n';
            }
          case 155: break;
          case 55: 
            { NuevoChar = '\t';
            }
          case 156: break;
          case 56: 
            { NuevoChar = '\r';
            }
          case 157: break;
          case 57: 
            { NuevoChar = '\"';
            }
          case 158: break;
          case 58: 
            { return symbol(sym.decimal, yytext().toLowerCase());
            }
          case 159: break;
          case 59: 
            { return symbol(sym.tresP, "...");
            }
          case 160: break;
          case 60: 
            { return symbol(sym.nil, yytext().toLowerCase());
            }
          case 161: break;
          case 61: 
            { return symbol(sym.not, yytext().toLowerCase());
            }
          case 162: break;
          case 62: 
            { return symbol(sym.nor, yytext().toLowerCase());
            }
          case 163: break;
          case 63: 
            { return symbol(sym.end, yytext().toLowerCase());
            }
          case 164: break;
          case 64: 
            { return symbol(sym.and, yytext().toLowerCase());
            }
          case 165: break;
          case 65: 
            { return symbol(sym.para, yytext().toLowerCase());
            }
          case 166: break;
          case 66: 
            { return symbol(sym.var, yytext().toLowerCase());
            }
          case 167: break;
          case 67: 
            { return symbol(sym.nand, yytext().toLowerCase());
            }
          case 168: break;
          case 68: 
            { return symbol(sym.verdadero, yytext().toLowerCase());
            }
          case 169: break;
          case 69: 
            { return symbol(sym.then, yytext().toLowerCase());
            }
          case 170: break;
          case 70: 
            { return symbol(sym.type, yytext().toLowerCase());
            }
          case 171: break;
          case 71: 
            { return symbol(sym.sino, yytext().toLowerCase());
            }
          case 172: break;
          case 72: 
            { return symbol(sym.salir, yytext().toLowerCase());
            }
          case 173: break;
          case 73: 
            { return symbol(sym.real,  yytext().toLowerCase());
            }
          case 174: break;
          case 74: 
            { return symbol(sym.leer, yytext().toLowerCase());
            }
          case 175: break;
          case 75: 
            { return symbol(sym.caso, yytext().toLowerCase());
            }
          case 176: break;
          case 76: 
            { return symbol(sym.character, yytext().toLowerCase());
            }
          case 177: break;
          case 77: 
            { return symbol(sym.con, yytext().toLowerCase());
            }
          case 178: break;
          case 78: 
            { return symbol(sym.word, yytext().toLowerCase());
            }
          case 179: break;
          case 79: 
            { return symbol(sym.free, yytext().toLowerCase());
            }
          case 180: break;
          case 80: 
            { return symbol(sym.uses, yytext().toLowerCase());
            }
          case 181: break;
          case 81: 
            { return symbol(sym.array, yytext().toLowerCase());
            }
          case 182: break;
          case 82: 
            { return symbol(sym.constante, yytext().toLowerCase());
            }
          case 183: break;
          case 83: 
            { return symbol(sym.begin, yytext().toLowerCase());
            }
          case 184: break;
          case 84: 
            { return symbol(sym.detener, yytext().toLowerCase());
            }
          case 185: break;
          case 85: 
            { return symbol(sym.escribir, yytext().toLowerCase());
            }
          case 186: break;
          case 86: 
            { return symbol(sym.mientras, yytext().toLowerCase());
            }
          case 187: break;
          case 87: 
            { return symbol(sym.falso, yytext().toLowerCase());
            }
          case 188: break;
          case 88: 
            { return symbol(sym.until, yytext().toLowerCase());
            }
          case 189: break;
          case 89: 
            { return symbol(sym.record, yytext().toLowerCase());
            }
          case 190: break;
          case 90: 
            { return symbol(sym.repeat, yytext().toLowerCase());
            }
          case 191: break;
          case 91: 
            { return symbol(sym.downto, yytext().toLowerCase());
            }
          case 192: break;
          case 92: 
            { return symbol(sym.sizeof, yytext().toLowerCase());
            }
          case 193: break;
          case 93: 
            { return symbol(sym.string, yytext().toLowerCase());
            }
          case 194: break;
          case 94: 
            { return symbol(sym.malloc, yytext().toLowerCase());
            }
          case 195: break;
          case 95: 
            { return symbol(sym.integer, yytext().toLowerCase());
            }
          case 196: break;
          case 96: 
            { return symbol(sym.bool, yytext().toLowerCase());
            }
          case 197: break;
          case 97: 
            { return symbol(sym.escribirln, yytext().toLowerCase());
            }
          case 198: break;
          case 98: 
            { return symbol(sym.program, yytext().toLowerCase());
            }
          case 199: break;
          case 99: 
            { return symbol(sym.continuar, yytext().toLowerCase());
            }
          case 200: break;
          case 100: 
            { return symbol(sym.function, yytext().toLowerCase());
            }
          case 201: break;
          case 101: 
            { return symbol(sym.procedure, yytext().toLowerCase());
            }
          case 202: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
