
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 06 01:22:55 CST 2019
//----------------------------------------------------

package SintacticoDosLang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int decimal = 3;
  public static final int numero = 2;
  public static final int cadena = 6;
  public static final int error = 1;
  public static final int identificador = 7;
  public static final int igual = 5;
  public static final int tipo = 4;
  public static final int EOF = 0;
}

