
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 10 01:09:13 CST 2019
//----------------------------------------------------

package SintacticoDosLang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int integer = 9;
  public static final int menos = 77;
  public static final int menorque = 66;
  public static final int mod = 46;
  public static final int dosP = 25;
  public static final int identificador = 8;
  public static final int punto = 58;
  public static final int character = 11;
  public static final int label = 45;
  public static final int repeat = 52;
  public static final int free = 29;
  public static final int div = 34;
  public static final int procedure = 50;
  public static final int dosPuntos = 63;
  public static final int corI = 23;
  public static final int mas = 76;
  public static final int cadena = 7;
  public static final int menorigual = 67;
  public static final int mientras = 59;
  public static final int corD = 24;
  public static final int sino = 37;
  public static final int decimal = 3;
  public static final int caso = 32;
  public static final int con = 60;
  public static final int file = 39;
  public static final int begin = 31;
  public static final int igualacion = 70;
  public static final int ir = 42;
  public static final int string = 14;
  public static final int in = 44;
  public static final int or = 48;
  public static final int set = 53;
  public static final int function = 41;
  public static final int mayorque = 68;
  public static final int constante = 33;
  public static final int caracter = 61;
  public static final int mayorigual = 69;
  public static final int of = 26;
  public static final int end = 38;
  public static final int nand = 72;
  public static final int uses = 62;
  public static final int bool = 12;
  public static final int real = 10;
  public static final int packed = 49;
  public static final int type = 17;
  public static final int and = 30;
  public static final int until = 56;
  public static final int to = 55;
  public static final int word = 13;
  public static final int malloc = 28;
  public static final int division = 79;
  public static final int sizeof = 27;
  public static final int EOF = 0;
  public static final int falso = 74;
  public static final int numero = 2;
  public static final int program = 51;
  public static final int potencia = 64;
  public static final int verdadero = 75;
  public static final int array = 22;
  public static final int error = 1;
  public static final int parenI = 19;
  public static final int diferente = 71;
  public static final int si = 43;
  public static final int parenD = 20;
  public static final int then = 54;
  public static final int UMENOS = 80;
  public static final int record = 15;
  public static final int hacer = 35;
  public static final int tresP = 21;
  public static final int por = 78;
  public static final int para = 40;
  public static final int coma = 18;
  public static final int modulo = 65;
  public static final int not = 47;
  public static final int downto = 36;
  public static final int igual = 5;
  public static final int nor = 73;
  public static final int nil = 16;
  public static final int var = 57;
  public static final int pComa = 6;
  public static final int tipo = 4;
}

