
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 26 11:49:03 CST 2019
//----------------------------------------------------

package SintacticoDosLang;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int integer = 8;
  public static final int menorque = 56;
  public static final int menos = 67;
  public static final int dosP = 24;
  public static final int identificador = 7;
  public static final int punto = 49;
  public static final int character = 10;
  public static final int repeat = 44;
  public static final int free = 28;
  public static final int escribirln = 76;
  public static final int procedure = 42;
  public static final int dosPuntos = 53;
  public static final int corI = 22;
  public static final int mas = 66;
  public static final int cadena = 6;
  public static final int menorigual = 57;
  public static final int mientras = 50;
  public static final int corD = 23;
  public static final int detener = 72;
  public static final int sino = 35;
  public static final int decimal = 3;
  public static final int caso = 31;
  public static final int con = 51;
  public static final int begin = 30;
  public static final int igualacion = 60;
  public static final int string = 13;
  public static final int or = 41;
  public static final int function = 38;
  public static final int mayorque = 58;
  public static final int caracter = 77;
  public static final int constante = 32;
  public static final int mayorigual = 59;
  public static final int of = 25;
  public static final int end = 36;
  public static final int nand = 62;
  public static final int uses = 52;
  public static final int bool = 11;
  public static final int real = 9;
  public static final int type = 16;
  public static final int and = 29;
  public static final int until = 47;
  public static final int to = 46;
  public static final int word = 12;
  public static final int malloc = 27;
  public static final int division = 69;
  public static final int sizeof = 26;
  public static final int EOF = 0;
  public static final int escribir = 75;
  public static final int leer = 71;
  public static final int falso = 64;
  public static final int numero = 2;
  public static final int program = 43;
  public static final int potencia = 54;
  public static final int verdadero = 65;
  public static final int array = 21;
  public static final int error = 1;
  public static final int parenI = 18;
  public static final int continuar = 73;
  public static final int diferente = 61;
  public static final int si = 39;
  public static final int parenD = 19;
  public static final int then = 45;
  public static final int UMENOS = 70;
  public static final int salir = 74;
  public static final int record = 14;
  public static final int hacer = 33;
  public static final int tresP = 20;
  public static final int por = 68;
  public static final int para = 37;
  public static final int coma = 17;
  public static final int modulo = 55;
  public static final int not = 40;
  public static final int downto = 34;
  public static final int igual = 4;
  public static final int nor = 63;
  public static final int nil = 15;
  public static final int var = 48;
  public static final int pComa = 5;
}

