/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TablaSimbolos;

/**
 * @author Pavel
 */
public class GenerarNativas4D {

    public String generarConcatenacion(Tabla tabla) {
        String codigo = "";
        String temp1 = tabla.getTemporal();
        String temp2 = tabla.getTemporal();
        String temp3 = tabla.getTemporal();
        String temp4 = tabla.getTemporal();
        String temp5 = tabla.getTemporal();
        String temp6 = tabla.getTemporal();
        String temp7 = tabla.getTemporal();
        String temp8 = tabla.getTemporal();

        String label1 = tabla.getEtiqueta();
        String label2 = tabla.getEtiqueta();
        String label3 = tabla.getEtiqueta();
        String label4 = tabla.getEtiqueta();

        codigo += "begin,,,concatenar_cadenas\n";
        codigo += "+,p,1," + temp1 + "\n";
        codigo += "=,stack," + temp1 + "," + temp2 + "\n";
        codigo += "+,p,2," + temp3 + "\n";
        codigo += "=,stack," + temp3 + "," + temp4 + "\n";
        codigo += "=,h,," + temp7;
        codigo += label1 + ":" + "\n";
        codigo += "=,heap," + temp2 + "," + temp5 + "\n";
        codigo += "je," + temp5 + ",0," + label2 + "\n";
        codigo += "=,h," + temp5 + ",heap" + "\n";
        codigo += "+,h,1,h\n";
        codigo += "+," + temp2 + ",1," + temp2 + "\n";
        codigo += "jmp,,," + label1 + "\n";
        codigo += label2 + ":" + "\n";

        codigo += label3 + ":" + "\n";
        codigo += "=,heap," + temp4 + "," + temp6 + "\n";
        codigo += "je," + temp6 + ",0," + label4 + "\n";
        codigo += "=,h," + temp6 + ",heap" + "\n";
        codigo += "+,h,1,h\n";
        codigo += "+," + temp4 + ",1," + temp4 + "\n";
        codigo += "jmp,,," + label3 + "\n";
        codigo += label4 + ":" + "\n";
        codigo += "=,h,0,heap" + "\n";
        codigo += "+,h,1,h\n";
        codigo += "+,p,0," + temp8 + "\n";
        codigo += "=," + temp8 + "," + temp7 + ",stack\n";
        codigo += "end,,,concatenar_cadenas" + "\n";
        return codigo;
    }

    public String generarConcatenacionStringChar(Tabla tabla) {
        String codigo = "";
        String temp1 = tabla.getTemporal();
        String temp2 = tabla.getTemporal();
        String temp3 = tabla.getTemporal();
        String temp4 = tabla.getTemporal();
        String temp5 = tabla.getTemporal();
        String temp7 = tabla.getTemporal();
        String temp8 = tabla.getTemporal();

        String label1 = tabla.getEtiqueta();
        String label2 = tabla.getEtiqueta();

        codigo += "begin,,,concatenar_Stringchar\n";
        codigo += "+,p,1," + temp1 + "\n";
        codigo += "=,stack," + temp1 + "," + temp2 + "\n";
        codigo += "+,p,2," + temp3 + "\n";
        codigo += "=,stack," + temp3 + "," + temp4 + "\n";
        codigo += "=,h,," + temp7;
        codigo += label1 + ":" + "\n";
        codigo += "=,heap," + temp2 + "," + temp5 + "\n";
        codigo += "je," + temp5 + ",0," + label2 + "\n";
        codigo += "=,h," + temp5 + ",heap" + "\n";
        codigo += "+,h,1,h\n";
        codigo += "+," + temp2 + ",1," + temp2 + "\n";
        codigo += "jmp,,," + label1 + "\n";
        codigo += label2 + ":" + "\n";

        codigo += "=,h," + temp4 + ",heap" + "\n";
        codigo += "+,h,1,h\n";

        codigo += "=,h,0,heap" + "\n";
        codigo += "+,h,1,h\n";
        codigo += "+,p,0," + temp8 + "\n";
        codigo += "=," + temp8 + "," + temp7 + ",stack\n";
        codigo += "end,,,concatenar_Stringchar" + "\n";
        return codigo;
    }

    public String generarConcatenacionCharString(Tabla tabla) {
        String codigo = "";
        String temp1 = tabla.getTemporal();
        String temp2 = tabla.getTemporal();
        String temp3 = tabla.getTemporal();
        String temp4 = tabla.getTemporal();
        String temp5 = tabla.getTemporal();
        String temp7 = tabla.getTemporal();
        String temp8 = tabla.getTemporal();

        String label1 = tabla.getEtiqueta();
        String label2 = tabla.getEtiqueta();

        codigo += "begin,,,concatenar_charString\n";
        codigo += "+,p,1," + temp1 + "\n";
        codigo += "=,stack," + temp1 + "," + temp2 + "\n";
        codigo += "+,p,2," + temp3 + "\n";
        codigo += "=,stack," + temp3 + "," + temp4 + "\n";
        codigo += "=,h,," + temp7;

        codigo += "=,h," + temp4 + ",heap" + "\n";
        codigo += "+,h,1,h\n";

        codigo += label1 + ":" + "\n";
        codigo += "=,heap," + temp2 + "," + temp5 + "\n";
        codigo += "je," + temp5 + ",0," + label2 + "\n";
        codigo += "=,h," + temp5 + ",heap" + "\n";
        codigo += "+,h,1,h\n";
        codigo += "+," + temp2 + ",1," + temp2 + "\n";
        codigo += "jmp,,," + label1 + "\n";
        codigo += label2 + ":" + "\n";


        codigo += "=,h,0,heap" + "\n";
        codigo += "+,h,1,h\n";
        codigo += "+,p,0," + temp8 + "\n";
        codigo += "=," + temp8 + "," + temp7 + ",stack\n";
        codigo += "end,,,concatenar_charString" + "\n";
        return codigo;
    }

    public String generarPrint(Tabla tabla) {
        String codigo = "";
        String temp1 = tabla.getTemporal();
        String temp2 = tabla.getTemporal();
        String temp3 = tabla.getTemporal();
        //String temp4 = tabla.getTemporal();
        String label1 = tabla.getEtiqueta();
        String label2 = tabla.getEtiqueta();

        codigo += "begin,,,print_str\n";
        codigo += "+,p,0," + temp1 + "\n";
        codigo += "=,stack," + temp1 + "," + temp2 + "\n";
        codigo += label2 + ":\n";
        codigo += "=,heap," + temp2 + "," + temp3 + "\n";
        codigo += "je," + temp3 + ",0," + label1 + "\n";
        codigo += "print(%c," + temp3 + ")\n";
        codigo += "+,1," + temp2 + "," + temp2 + "\n";
        codigo += "jmp,,," + label2 + "\n";
        codigo += label1 + ":\n";
        codigo += "print(%c,13)\n";
        //codigo += "print(%c,10)\n";
        codigo += "end,,,print_str\n";
        return codigo;
    }

    public String generarTrunk(Tabla tabla) {
        String codigo = "";
        codigo += "begin,,,trunk_primitiva\n";
        String temp1 = tabla.getTemporal();
        String temp2 = tabla.getTemporal();
        String temp3 = tabla.getTemporal();
        String temp4 = tabla.getTemporal();
        String temp5 = tabla.getTemporal();
        codigo += "+,p,0," + temp1 + "\n";
        codigo += "=,stack," + temp1 + "," + temp2 + "\n";
        codigo += "%," + temp2 + ",1," + temp3 + "\n";
        codigo += "-," + temp2 + "," + temp3 + "," + temp4 + "\n";
        codigo += "+,p,1," + temp5 + "\n";
        codigo += "=," + temp5 + "," + temp4 + ",stack\n";
        codigo += "end,,,trunk_primitiva\n";
        return codigo;
    }

    public String generarRound(Tabla tabla) {
        String codigo = "";
        codigo += "begin,,,round_primitiva\n";
        String temp1 = tabla.getTemporal();
        String temp2 = tabla.getTemporal();
        String temp3 = tabla.getTemporal();
        String temp4 = tabla.getTemporal();
        String temp5 = tabla.getTemporal();
        String label1 = tabla.getEtiqueta();
        codigo += "+,p,0," + temp1 + "\n";
        codigo += "=,stack," + temp1 + "," + temp2 + "\n";
        codigo += "%," + temp2 + ",1," + temp3 + "\n";
        codigo += "-," + temp2 + "," + temp3 + "," + temp4 + "\n";
        codigo += "jl," + temp3 + ",0.5," + label1 + "\n";
        codigo += "+," + temp4 + ",1," + temp4 + "\n";
        codigo += label1 + ":\n";
        codigo += "+,p,1," + temp5 + "\n";
        codigo += "=," + temp5 + "," + temp4 + ",stack\n";
        codigo += "end,,,round_primitiva\n";
        return codigo;
    }

    public String generarChartAt(Tabla tabla) {
        String codigo = "";
        String temp1 = tabla.getTemporal();
        String temp2 = tabla.getTemporal();
        String temp3 = tabla.getTemporal();
        String temp4 = tabla.getTemporal();
        String temp5 = tabla.getTemporal();
        String temp6 = tabla.getTemporal();
        String temp7 = tabla.getTemporal();

        codigo += "begin,,,CharAt_primitiva\n";
        codigo += "+,p,1," + temp1 + "\n";
        codigo += "=,stack," + temp1 + "," + temp2 + "\n";
        codigo += "+,p,2," + temp3 + "\n";
        codigo += "=,stack," + temp3 + "," + temp4 + "\n";
        codigo += "+," + temp2 + ", " + temp4 + "," + temp5 + "\n";
        codigo += "=,heap," + temp5 + "," + temp6 + "\n";
        codigo += "+,p,0," + temp7 + "\n";
        codigo += "=," + temp7 + "," + temp6 + ",stack\n";
        codigo += "end,,,CharAt_primitiva" + "\n";
        return codigo;
    }

    public String generarLenght(Tabla tabla) {
        String codigo = "";
        String temp1 = tabla.getTemporal();
        String temp2 = tabla.getTemporal();
        String temp3 = tabla.getTemporal();
        String temp4 = tabla.getTemporal();
        String temp5 = tabla.getTemporal();
        String label1 = tabla.getEtiqueta();
        String label2 = tabla.getEtiqueta();

        codigo += "begin,,,lenght_primitiva\n";
        codigo += "+,p,1," + temp1 + "\n";
        codigo += "=,stack," + temp1 + "," + temp2 + "\n";
        codigo += "=,0,," + temp3 + "\n";
        codigo += label2 + ":\n";
        codigo += "=,heap," + temp2 + "," + temp4 + "\n";
        codigo += "je," + temp4 + ",0," + label1 + "\n";
        codigo += "+,1," + temp3 + "," + temp3 + "\n";
        codigo += "+,1," + temp2 + "," + temp2 + "\n";
        codigo += "jmp,,," + label2 + "\n";
        codigo += label1 + ":\n";
        codigo += "+,p,0," + temp5 + "\n";
        codigo += "=," + temp5 + "," + temp3 + ",stack\n";
        codigo += "end,,,lenght_primitiva\n";
        return codigo;
    }

    public String generaReplace(Tabla tabla) {
        String codigo = "";
        String temp0 = tabla.getTemporal();
        String temp1 = tabla.getTemporal();
        String temp2 = tabla.getTemporal();
        String temp3 = tabla.getTemporal();
        String temp4 = tabla.getTemporal();
        String temp5 = tabla.getTemporal();
        String temp6 = tabla.getTemporal();
        String temp7 = tabla.getTemporal();
        String temp8 = tabla.getTemporal();
        String temp9 = tabla.getTemporal();
        String temp10 = tabla.getTemporal();
        String temp11 = tabla.getTemporal();
        String temp12 = tabla.getTemporal();
        String temp13 = tabla.getTemporal();
        String temp14 = tabla.getTemporal();
        String temp15 = tabla.getTemporal();
        String temp16 = tabla.getTemporal();
        String temp17 = tabla.getTemporal();
        String temp18 = tabla.getTemporal();
        String temp19 = tabla.getTemporal();
        String temp20 = tabla.getTemporal();
        String temp21 = tabla.getTemporal();
        String temp22 = tabla.getTemporal();
        String temp23 = tabla.getTemporal();
        String temp24 = tabla.getTemporal();
        String temp25 = tabla.getTemporal();
        String temp26 = tabla.getTemporal();
        String temp27 = tabla.getTemporal();
        String temp28 = tabla.getTemporal();
        String temp29 = tabla.getTemporal();
        String temp30 = tabla.getTemporal();
        String temp31 = tabla.getTemporal();
        String temp32 = tabla.getTemporal();
        String temp33 = tabla.getTemporal();
        String temp34 = tabla.getTemporal();
        String temp35 = tabla.getTemporal();
        String temp36 = tabla.getTemporal();
        String temp37 = tabla.getTemporal();
        String temp38 = tabla.getTemporal();
        String temp39 = tabla.getTemporal();
        String temp40 = tabla.getTemporal();
        String temp41 = tabla.getTemporal();
        String temp42 = tabla.getTemporal();
        String temp43 = tabla.getTemporal();
        String temp44 = tabla.getTemporal();
        String temp45 = tabla.getTemporal();
        String temp46 = tabla.getTemporal();
        String temp47 = tabla.getTemporal();
        String temp48 = tabla.getTemporal();
        String temp49 = tabla.getTemporal();
        String temp50 = tabla.getTemporal();
        String temp51 = tabla.getTemporal();
        String temp52 = tabla.getTemporal();
        String temp53 = tabla.getTemporal();
        String temp54 = tabla.getTemporal();
        String temp55 = tabla.getTemporal();
        String temp56 = tabla.getTemporal();
        String temp57 = tabla.getTemporal();
        String temp58 = tabla.getTemporal();
        String temp59 = tabla.getTemporal();
        String temp60 = tabla.getTemporal();
        String temp61 = tabla.getTemporal();
        String temp62 = tabla.getTemporal();
        String temp63 = tabla.getTemporal();
        String temp64 = tabla.getTemporal();
        String temp65 = tabla.getTemporal();
        String temp66 = tabla.getTemporal();
        String temp67 = tabla.getTemporal();
        String temp68 = tabla.getTemporal();
        String temp69 = tabla.getTemporal();
        String temp70 = tabla.getTemporal();
        String temp71 = tabla.getTemporal();
        String temp72 = tabla.getTemporal();
        String temp73 = tabla.getTemporal();
        String temp74 = tabla.getTemporal();
        String temp75 = tabla.getTemporal();
        String temp76 = tabla.getTemporal();
        String temp77 = tabla.getTemporal();
        String temp78 = tabla.getTemporal();
        String temp79 = tabla.getTemporal();
        String temp80 = tabla.getTemporal();
        String temp81 = tabla.getTemporal();
        String temp82 = tabla.getTemporal();
        String temp83 = tabla.getTemporal();
        String temp84 = tabla.getTemporal();
        String temp85 = tabla.getTemporal();
        String temp86 = tabla.getTemporal();
        String temp87 = tabla.getTemporal();
        String temp88 = tabla.getTemporal();
        String temp89 = tabla.getTemporal();
        String temp90 = tabla.getTemporal();
        String temp91 = tabla.getTemporal();
        String temp92 = tabla.getTemporal();
        String temp93 = tabla.getTemporal();
        String temp94 = tabla.getTemporal();
        String temp95 = tabla.getTemporal();
        String temp96 = tabla.getTemporal();
        String temp97 = tabla.getTemporal();
        String temp98 = tabla.getTemporal();
        String temp99 = tabla.getTemporal();
        String temp100 = tabla.getTemporal();
        String temp101 = tabla.getTemporal();
        String temp102 = tabla.getTemporal();
        String temp103 = tabla.getTemporal();
        String temp104 = tabla.getTemporal();
        String temp105 = tabla.getTemporal();
        String temp106 = tabla.getTemporal();
        String temp107 = tabla.getTemporal();
        String temp108 = tabla.getTemporal();
        String temp109 = tabla.getTemporal();
        String temp110 = tabla.getTemporal();
        String temp111 = tabla.getTemporal();
        String temp112 = tabla.getTemporal();
        String temp113 = tabla.getTemporal();
        String temp114 = tabla.getTemporal();
        String temp115 = tabla.getTemporal();
        String temp116 = tabla.getTemporal();
        String temp117 = tabla.getTemporal();
        String temp118 = tabla.getTemporal();
        String temp119 = tabla.getTemporal();
        String temp120 = tabla.getTemporal();
        String temp121 = tabla.getTemporal();
        String temp122 = tabla.getTemporal();
        String temp123 = tabla.getTemporal();
        String temp124 = tabla.getTemporal();
        String temp125 = tabla.getTemporal();
        String temp126 = tabla.getTemporal();
        String temp127 = tabla.getTemporal();
        String temp128 = tabla.getTemporal();
        String temp129 = tabla.getTemporal();
        String temp130 = tabla.getTemporal();
        String temp131 = tabla.getTemporal();
        String temp132 = tabla.getTemporal();
        String temp133 = tabla.getTemporal();
        String temp134 = tabla.getTemporal();
        String temp135 = tabla.getTemporal();
        String temp136 = tabla.getTemporal();
        String temp137 = tabla.getTemporal();
        String temp138 = tabla.getTemporal();
        String temp139 = tabla.getTemporal();
        String temp140 = tabla.getTemporal();
        String temp141 = tabla.getTemporal();
        String temp142 = tabla.getTemporal();
        String temp143 = tabla.getTemporal();
        String temp144 = tabla.getTemporal();
        String temp145 = tabla.getTemporal();
        String temp146 = tabla.getTemporal();
        String temp147 = tabla.getTemporal();
        String temp148 = tabla.getTemporal();
        String temp149 = tabla.getTemporal();
        String temp150 = tabla.getTemporal();
        String temp151 = tabla.getTemporal();
        String temp152 = tabla.getTemporal();
        String temp153 = tabla.getTemporal();
        String temp154 = tabla.getTemporal();
        String temp155 = tabla.getTemporal();
        String temp156 = tabla.getTemporal();
        String temp157 = tabla.getTemporal();
        String temp158 = tabla.getTemporal();
        String temp159 = tabla.getTemporal();
        String temp160 = tabla.getTemporal();
        String temp161 = tabla.getTemporal();
        String temp162 = tabla.getTemporal();
        String temp163 = tabla.getTemporal();
        String temp164 = tabla.getTemporal();
        String temp165 = tabla.getTemporal();
        String temp166 = tabla.getTemporal();
        String temp167 = tabla.getTemporal();
        String temp168 = tabla.getTemporal();
        String temp169 = tabla.getTemporal();
        String temp170 = tabla.getTemporal();
        String temp171 = tabla.getTemporal();
        String temp172 = tabla.getTemporal();
        String temp173 = tabla.getTemporal();
        String temp174 = tabla.getTemporal();
        String temp175 = tabla.getTemporal();
        String temp176 = tabla.getTemporal();
        String temp177 = tabla.getTemporal();
        String temp178 = tabla.getTemporal();
        String temp179 = tabla.getTemporal();
        String temp180 = tabla.getTemporal();
        String temp181 = tabla.getTemporal();
        String temp182 = tabla.getTemporal();
        String temp183 = tabla.getTemporal();
        String temp184 = tabla.getTemporal();
        String temp185 = tabla.getTemporal();
        String temp186 = tabla.getTemporal();
        String temp187 = tabla.getTemporal();
        String temp188 = tabla.getTemporal();
        String temp189 = tabla.getTemporal();
        String temp190 = tabla.getTemporal();
        String temp191 = tabla.getTemporal();
        String temp192 = tabla.getTemporal();
        String temp193 = tabla.getTemporal();
        String temp194 = tabla.getTemporal();
        String temp195 = tabla.getTemporal();
        String temp196 = tabla.getTemporal();
        String temp197 = tabla.getTemporal();
        String temp198 = tabla.getTemporal();
        String temp199 = tabla.getTemporal();
        String temp200 = tabla.getTemporal();
        String temp201 = tabla.getTemporal();
        String temp202 = tabla.getTemporal();
        String temp203 = tabla.getTemporal();
        String temp204 = tabla.getTemporal();
        String temp205 = tabla.getTemporal();
        String temp206 = tabla.getTemporal();
        String temp207 = tabla.getTemporal();
        String temp208 = tabla.getTemporal();
        String temp209 = tabla.getTemporal();
        String temp210 = tabla.getTemporal();
        String temp211 = tabla.getTemporal();
        String temp212 = tabla.getTemporal();
        String temp213 = tabla.getTemporal();
        String temp214 = tabla.getTemporal();
        String temp215 = tabla.getTemporal();
        String temp216 = tabla.getTemporal();
        String temp217 = tabla.getTemporal();
        String temp218 = tabla.getTemporal();
        String temp219 = tabla.getTemporal();
        String temp220 = tabla.getTemporal();
        String temp221 = tabla.getTemporal();
        String temp222 = tabla.getTemporal();
        String temp223 = tabla.getTemporal();
        String temp224 = tabla.getTemporal();
        String temp225 = tabla.getTemporal();
        String temp226 = tabla.getTemporal();
        String temp227 = tabla.getTemporal();
        String temp228 = tabla.getTemporal();
        String temp229 = tabla.getTemporal();
        String temp230 = tabla.getTemporal();
        String temp231 = tabla.getTemporal();
        String temp232 = tabla.getTemporal();
        String temp233 = tabla.getTemporal();
        String temp234 = tabla.getTemporal();
        String temp235 = tabla.getTemporal();
        String temp236 = tabla.getTemporal();
        String temp237 = tabla.getTemporal();
        String temp238 = tabla.getTemporal();
        String temp239 = tabla.getTemporal();
        String temp240 = tabla.getTemporal();
        String temp241 = tabla.getTemporal();
        String temp242 = tabla.getTemporal();
        String temp243 = tabla.getTemporal();
        String temp244 = tabla.getTemporal();
        String temp245 = tabla.getTemporal();
        String temp246 = tabla.getTemporal();
        String temp247 = tabla.getTemporal();
        String temp248 = tabla.getTemporal();
        String temp249 = tabla.getTemporal();
        String temp250 = tabla.getTemporal();
        String temp251 = tabla.getTemporal();
        String temp252 = tabla.getTemporal();
        String temp253 = tabla.getTemporal();
        String temp254 = tabla.getTemporal();
        String temp255 = tabla.getTemporal();
        String temp256 = tabla.getTemporal();
        String temp257 = tabla.getTemporal();
        String temp258 = tabla.getTemporal();
        String temp259 = tabla.getTemporal();
        String temp260 = tabla.getTemporal();
        String temp261 = tabla.getTemporal();
        String temp262 = tabla.getTemporal();
        String temp263 = tabla.getTemporal();
        String temp264 = tabla.getTemporal();
        String temp265 = tabla.getTemporal();
        String temp266 = tabla.getTemporal();
        String temp267 = tabla.getTemporal();
        String temp268 = tabla.getTemporal();
        String label0 = tabla.getEtiqueta();
        String label1 = tabla.getEtiqueta();
        String label2 = tabla.getEtiqueta();
        String label3 = tabla.getEtiqueta();
        String label4 = tabla.getEtiqueta();
        String label5 = tabla.getEtiqueta();
        String label6 = tabla.getEtiqueta();
        String label7 = tabla.getEtiqueta();
        String label8 = tabla.getEtiqueta();
        String label9 = tabla.getEtiqueta();
        String label10 = tabla.getEtiqueta();
        String label11 = tabla.getEtiqueta();
        String label12 = tabla.getEtiqueta();
        String label13 = tabla.getEtiqueta();
        String label14 = tabla.getEtiqueta();
        String label15 = tabla.getEtiqueta();
        String label16 = tabla.getEtiqueta();
        String label17 = tabla.getEtiqueta();
        String label18 = tabla.getEtiqueta();
        String label19 = tabla.getEtiqueta();
        String label20 = tabla.getEtiqueta();
        String label21 = tabla.getEtiqueta();
        String label22 = tabla.getEtiqueta();
        String label23 = tabla.getEtiqueta();
        String label24 = tabla.getEtiqueta();
        String label25 = tabla.getEtiqueta();
        String label26 = tabla.getEtiqueta();
        String label27 = tabla.getEtiqueta();
        String label28 = tabla.getEtiqueta();
        String label29 = tabla.getEtiqueta();
        String label30 = tabla.getEtiqueta();
        String label31 = tabla.getEtiqueta();

        codigo += "begin,,,reemplazar_primitiva\n";
        codigo += "+,p,0," + temp0 + "\n";
        codigo += "=," + temp0 + ",-1,STACK\n";
        codigo += "=,3,," + temp1 + "\n";
        codigo += "+,p," + temp1 + "," + temp2 + "\n";
        codigo += "=,h,," + temp3 + "\n";
        codigo += "=,h,0,heap\n";
        codigo += "+,h,1,h\n";
        codigo += "=," + temp3 + ",," + temp4 + "\n";
        codigo += "=, " + temp2 + ", " + temp4 + ", STACK\n";
        codigo += "=,4,," + temp5 + "\n";
        codigo += "+,p," + temp5 + "," + temp6 + "\n";
        codigo += "=,0,," + temp7 + "\n";
        codigo += "=, " + temp6 + ", " + temp7 + ", STACK\n";
        codigo += "=,5,," + temp8 + "\n";
        codigo += "+,p," + temp8 + "," + temp9 + "\n";
        codigo += "=,0,," + temp10 + "\n";
        codigo += "=, " + temp9 + ", " + temp10 + ", STACK\n";
        codigo += "=,6,," + temp11 + "\n";
        codigo += "+,p," + temp11 + "," + temp12 + "\n";
        codigo += "=,0,," + temp13 + "\n";
        codigo += "=, " + temp12 + ", " + temp13 + ", STACK\n";
        codigo += "=,7,," + temp14 + "\n";
        codigo += "+,p," + temp14 + "," + temp15 + "\n";
        codigo += "=,0,," + temp16 + "\n";
        codigo += "=, " + temp15 + ", " + temp16 + ", STACK\n";
        codigo += "=,8,," + temp17 + "\n";
        codigo += "+,p," + temp17 + "," + temp18 + "\n";
        codigo += "=,0,," + temp19 + "\n";
        codigo += "=, " + temp18 + ", " + temp19 + ", STACK\n";
        codigo += "=,9,," + temp20 + "\n";
        codigo += "+,p," + temp20 + "," + temp21 + "\n";
        codigo += "=,32,," + temp22 + "\n";
        codigo += "=, " + temp21 + ", " + temp22 + ", STACK\n";
        codigo += "=,10,," + temp23 + "\n";
        codigo += "+,p," + temp23 + "," + temp24 + "\n";
        codigo += "=,0,," + temp25 + "\n";
        codigo += "=, " + temp24 + ", " + temp25 + ", STACK\n";
        codigo += "=,7,," + temp27 + "// Id = sizecad1\n";
        codigo += "=," + temp27 + ",," + temp26 + "\n";
        codigo += "=," + temp26 + ",," + temp28 + "\n";
        codigo += "=,1,," + temp31 + "// Id = cad1\n";
        codigo += "+,p," + temp31 + "," + temp32 + "\n";
        codigo += "=,STACK," + temp32 + "," + temp33 + "\n";
        codigo += "=," + temp33 + ",," + temp30 + "\n";
        codigo += "=," + temp30 + ",," + temp34 + "\n";
        codigo += "+,p,11,p\n";
        codigo += "+,p,0," + temp35 + "\n";
        codigo += "=," + temp35 + ",-1,STACK\n";
        codigo += "+,p,1," + temp36 + "\n";
        codigo += "=," + temp36 + "," + temp34 + ",STACK\n";
        codigo += "call,,,lenght_primitiva\n";
        codigo += "+,p,0," + temp37 + "\n";
        codigo += "=,STACK," + temp37 + "," + temp38 + "\n";
        codigo += "-,p,11,p\n";
        codigo += "+,p," + temp28 + "," + temp29 + "\n";
        codigo += "=," + temp29 + "," + temp38 + ",STACK\n";
        codigo += "=,8,," + temp40 + "// Id = sizecad2\n";
        codigo += "=," + temp40 + ",," + temp39 + "\n";
        codigo += "=," + temp39 + ",," + temp41 + "\n";
        codigo += "=,2,," + temp44 + "// Id = cad2\n";
        codigo += "+,p," + temp44 + "," + temp45 + "\n";
        codigo += "=,STACK," + temp45 + "," + temp46 + "\n";
        codigo += "=," + temp46 + ",," + temp43 + "\n";
        codigo += "=," + temp43 + ",," + temp47 + "\n";
        codigo += "+,p,11,p\n";
        codigo += "+,p,0," + temp48 + "\n";
        codigo += "=," + temp48 + ",-1,STACK\n";
        codigo += "+,p,1," + temp49 + "\n";
        codigo += "=," + temp49 + "," + temp47 + ",STACK\n";
        codigo += "call,,,lenght_primitiva\n";
        codigo += "+,p,0," + temp50 + "\n";
        codigo += "=,STACK," + temp50 + "," + temp51 + "\n";
        codigo += "-,p,11,p\n";
        codigo += "// Fin llamada lenght\n";
        codigo += "+,p," + temp41 + "," + temp42 + "\n";
        codigo += "=," + temp42 + "," + temp51 + ",STACK\n";
        codigo += "=,7,," + temp53 + "// Id = sizecad1\n";
        codigo += "+,p," + temp53 + "," + temp54 + "\n";
        codigo += "=,STACK," + temp54 + "," + temp55 + "\n";
        codigo += "=," + temp55 + ",," + temp52 + "\n";
        codigo += "=," + temp52 + ",," + temp56 + "\n";
        codigo += "=,8,," + temp58 + "// Id = sizecad2\n";
        codigo += "+,p," + temp58 + "," + temp59 + "\n";
        codigo += "=,STACK," + temp59 + "," + temp60 + "\n";
        codigo += "=," + temp60 + ",," + temp57 + "\n";
        codigo += "=," + temp57 + ",," + temp61 + "\n";
        codigo += "jg," + temp56 + "," + temp61 + "," + label3 + "\n";
        codigo += "=,0,," + temp62 + "\n";
        codigo += "jmp,,," + label4 + "\n";
        codigo += "" + label3 + ":\n";
        codigo += "=,1,," + temp62 + "\n";
        codigo += "" + label4 + ":\n";
        codigo += "=," + temp62 + ",," + temp63 + "\n";
        codigo += "// Fin operacion\n";
        codigo += "je," + temp63 + ",1," + label0 + "\n";
        codigo += "jmp,,," + label1 + "\n";
        codigo += "" + label0 + ":\n";
        codigo += "=,6,," + temp67 + "// Id = j\n";
        codigo += "=," + temp67 + ",," + temp66 + "\n";
        codigo += "=," + temp66 + ",," + temp68 + "\n";
        codigo += "=,0,," + temp70 + "\n";
        codigo += "+,p," + temp68 + "," + temp69 + "\n";
        codigo += "=," + temp69 + "," + temp70 + ",STACK\n";
        codigo += "=,0,," + temp71 + "\n";
        codigo += "=," + temp71 + ",," + temp65 + "\n";
        codigo += "" + label5 + ":\n";
        codigo += "=,6,," + temp73 + "// Id = j\n";
        codigo += "+,p," + temp73 + "," + temp74 + "\n";
        codigo += "=,STACK," + temp74 + "," + temp75 + "\n";
        codigo += "=," + temp75 + ",," + temp72 + "\n";
        codigo += "=," + temp72 + ",," + temp76 + "\n";
        codigo += "=,7,," + temp78 + "// Id = sizecad1\n";
        codigo += "+,p," + temp78 + "," + temp79 + "\n";
        codigo += "=,STACK," + temp79 + "," + temp80 + "\n";
        codigo += "=," + temp80 + ",," + temp77 + "\n";
        codigo += "=," + temp77 + ",," + temp81 + "\n";
        codigo += "=,1,," + temp82 + "\n";
        codigo += "-," + temp81 + "," + temp82 + "," + temp83 + "\n";
        codigo += "jle," + temp76 + "," + temp83 + "," + label7 + "\n";
        codigo += "=,0,," + temp84 + "\n";
        codigo += "jmp,,," + label8 + "\n";
        codigo += "" + label7 + ":\n";
        codigo += "=,1,," + temp84 + "\n";
        codigo += "" + label8 + ":\n";
        codigo += "=," + temp84 + ",," + temp85 + "\n";
        codigo += "=," + temp85 + ",," + temp64 + "\n";
        codigo += "je," + temp64 + ",0," + label6 + "\n";
        codigo += "=,6,," + temp87 + "// Id = j\n";
        codigo += "+,p," + temp87 + "," + temp88 + "\n";
        codigo += "=,STACK," + temp88 + "," + temp89 + "\n";
        codigo += "=," + temp89 + ",," + temp86 + "\n";
        codigo += "=," + temp86 + ",," + temp90 + "\n";
        codigo += "=,8,," + temp92 + "// Id = sizecad2\n";
        codigo += "+,p," + temp92 + "," + temp93 + "\n";
        codigo += "=,STACK," + temp93 + "," + temp94 + "\n";
        codigo += "=," + temp94 + ",," + temp91 + "\n";
        codigo += "=," + temp91 + ",," + temp95 + "\n";
        codigo += "+," + temp90 + "," + temp95 + "," + temp96 + "\n";
        codigo += "=,7,," + temp98 + "// Id = sizecad1\n";
        codigo += "+,p," + temp98 + "," + temp99 + "\n";
        codigo += "=,STACK," + temp99 + "," + temp100 + "\n";
        codigo += "=," + temp100 + ",," + temp97 + "\n";
        codigo += "=," + temp97 + ",," + temp101 + "\n";
        codigo += "jle," + temp96 + "," + temp101 + "," + label12 + "\n";
        codigo += "=,0,," + temp102 + "\n";
        codigo += "jmp,,," + label13 + "\n";
        codigo += "" + label12 + ":\n";
        codigo += "=,1,," + temp102 + "\n";
        codigo += "" + label13 + ":\n";
        codigo += "=," + temp102 + ",," + temp103 + "\n";
        codigo += "=,10,," + temp105 + "// Id = encontrado\n";
        codigo += "+,p," + temp105 + "," + temp106 + "\n";
        codigo += "=,STACK," + temp106 + "," + temp107 + "\n";
        codigo += "=," + temp107 + ",," + temp104 + "\n";
        codigo += "=," + temp104 + ",," + temp108 + "\n";
        codigo += "je," + temp108 + ",1," + label14 + "\n";
        codigo += "=,1,," + temp109 + "\n";
        codigo += "jmp,,," + label15 + "\n";
        codigo += "" + label14 + ":\n";
        codigo += "=,0,," + temp109 + "\n";
        codigo += "" + label15 + ":\n";
        codigo += "=,0,," + temp110 + "\n";
        codigo += "je," + temp103 + ",1," + label16 + "\n";
        codigo += "jmp,,," + label17 + "\n";
        codigo += "" + label16 + ":\n";
        codigo += "je," + temp109 + ",1," + label18 + "\n";
        codigo += "jmp,,," + label19 + "\n";
        codigo += "" + label18 + ":\n";
        codigo += "=,1,," + temp110 + "\n";
        codigo += "" + label17 + ":\n";
        codigo += "" + label19 + ":\n";
        codigo += "// Fin operacion\n";
        codigo += "je," + temp110 + ",1," + label9 + "\n";
        codigo += "jmp,,," + label10 + "\n";
        codigo += "" + label9 + ":\n"; // Condicion verdadera\n";
        codigo += "=,5,," + temp114 + "// Id = i\n";
        codigo += "=," + temp114 + ",," + temp113 + "\n";
        codigo += "=," + temp113 + ",," + temp115 + "\n";
        codigo += "=,0,," + temp117 + "\n";
        codigo += "+,p," + temp115 + "," + temp116 + "\n";
        codigo += "=," + temp116 + "," + temp117 + ",STACK\n";
        codigo += "=,0,," + temp118 + "\n";
        codigo += "=," + temp118 + ",," + temp112 + "\n";
        codigo += "" + label20 + ":\n";
        codigo += "=,5,," + temp120 + "// Id = i\n";
        codigo += "+,p," + temp120 + "," + temp121 + "\n";
        codigo += "=,STACK," + temp121 + "," + temp122 + "\n";
        codigo += "=," + temp122 + ",," + temp119 + "\n";
        codigo += "=," + temp119 + ",," + temp123 + "\n";
        codigo += "=,8,," + temp125 + "// Id = sizecad2\n";
        codigo += "+,p," + temp125 + "," + temp126 + "\n";
        codigo += "=,STACK," + temp126 + "," + temp127 + "\n";
        codigo += "=," + temp127 + ",," + temp124 + "\n";
        codigo += "=," + temp124 + ",," + temp128 + "\n";
        codigo += "=,1,," + temp129 + "\n";
        codigo += "-," + temp128 + "," + temp129 + "," + temp130 + "\n";
        codigo += "jle," + temp123 + "," + temp130 + "," + label22 + "\n";
        codigo += "=,0,," + temp131 + "\n";
        codigo += "jmp,,," + label23 + "\n";
        codigo += "" + label22 + ":\n";
        codigo += "=,1,," + temp131 + "\n";
        codigo += "" + label23 + ":\n";
        codigo += "=," + temp131 + ",," + temp132 + "\n";
        codigo += "// Fin operacion\n";
        codigo += "=," + temp132 + ",," + temp111 + "\n";
        codigo += "je," + temp111 + ",0," + label21 + "\n";
        codigo += "=,4,," + temp134 + "// Id = indice\n";
        codigo += "=," + temp134 + ",," + temp133 + "\n";
        codigo += "=," + temp133 + ",," + temp135 + "\n";
        codigo += "=,6,," + temp138 + "// Id = j\n";
        codigo += "+,p," + temp138 + "," + temp139 + "\n";
        codigo += "=,STACK," + temp139 + "," + temp140 + "\n";
        codigo += "=," + temp140 + ",," + temp137 + "\n";
        codigo += "=," + temp137 + ",," + temp141 + "\n";
        codigo += "=,5,," + temp143 + "// Id = i\n";
        codigo += "+,p," + temp143 + "," + temp144 + "\n";
        codigo += "=,STACK," + temp144 + "," + temp145 + "\n";
        codigo += "=," + temp145 + ",," + temp142 + "\n";
        codigo += "=," + temp142 + ",," + temp146 + "\n";
        codigo += "+," + temp141 + "," + temp146 + "," + temp147 + "\n";
        codigo += "+,p," + temp135 + "," + temp136 + "\n";
        codigo += "=," + temp136 + "," + temp147 + ",STACK\n";
        codigo += "=,1,," + temp149 + "// Id = cad1\n";
        codigo += "+,p," + temp149 + "," + temp150 + "\n";
        codigo += "=,STACK," + temp150 + "," + temp151 + "\n";
        codigo += "=," + temp151 + ",," + temp148 + "\n";
        codigo += "=," + temp148 + ",," + temp152 + "\n";
        codigo += "=,4,," + temp154 + "// Id = indice\n";
        codigo += "+,p," + temp154 + "," + temp155 + "\n";
        codigo += "=,STACK," + temp155 + "," + temp156 + "\n";
        codigo += "=," + temp156 + ",," + temp153 + "\n";
        codigo += "=," + temp153 + ",," + temp157 + "\n";
        codigo += "+,p,11,p\n";
        codigo += "+,p,0," + temp158 + "\n";
        codigo += "=," + temp158 + ",-1,STACK\n";
        codigo += "+,p,1," + temp159 + "\n";
        codigo += "=," + temp159 + "," + temp152 + ",STACK\n";
        codigo += "+,p,2," + temp160 + "\n";
        codigo += "=," + temp160 + "," + temp157 + ",STACK\n";
        codigo += "call,,,CharAt_primitiva\n";
        codigo += "+,p,0," + temp161 + "\n";
        codigo += "=,STACK," + temp161 + "," + temp162 + "\n";
        codigo += "-,p,11,p\n";
        codigo += "=,2,," + temp164 + "// Id = cad2\n";
        codigo += "+,p," + temp164 + "," + temp165 + "\n";
        codigo += "=,STACK," + temp165 + "," + temp166 + "\n";
        codigo += "=," + temp166 + ",," + temp163 + "\n";
        codigo += "=," + temp163 + ",," + temp167 + "\n";
        codigo += "=,5,," + temp169 + "// Id = i\n";
        codigo += "+,p," + temp169 + "," + temp170 + "\n";
        codigo += "=,STACK," + temp170 + "," + temp171 + "\n";
        codigo += "=," + temp171 + ",," + temp168 + "\n";
        codigo += "=," + temp168 + ",," + temp172 + "\n";
        codigo += "+,p,11,p\n";
        codigo += "+,p,0," + temp173 + "\n";
        codigo += "=," + temp173 + ",-1,STACK\n";
        codigo += "+,p,1," + temp174 + "\n";
        codigo += "=," + temp174 + "," + temp167 + ",STACK\n";
        codigo += "+,p,2," + temp175 + "\n";
        codigo += "=," + temp175 + "," + temp172 + ",STACK\n";
        codigo += "call,,,CharAt_primitiva\n";
        codigo += "+,p,0," + temp176 + "\n";
        codigo += "=,STACK," + temp176 + "," + temp177 + "\n";
        codigo += "-,p,11,p\n";
        codigo += "// Fin llamada charAt\n";
        codigo += "je," + temp162 + "," + temp177 + "," + label27 + "\n";
        codigo += "=,0,," + temp178 + "\n";
        codigo += "jmp,,," + label28 + "\n";
        codigo += "" + label27 + ":\n";
        codigo += "=,1,," + temp178 + "\n";
        codigo += "" + label28 + ":\n";
        codigo += "=," + temp178 + ",," + temp179 + "\n";
        codigo += "je," + temp179 + ",1," + label24 + "\n";
        codigo += "jmp,,," + label25 + "\n";
        codigo += "" + label24 + ":\n"; // Condicion verdadera\n";
        codigo += "=,6,," + temp181 + "// Id = j\n";
        codigo += "=," + temp181 + ",," + temp180 + "\n";
        codigo += "=," + temp180 + ",," + temp182 + "\n";
        codigo += "=,6,," + temp185 + "// Id = j\n";
        codigo += "+,p," + temp185 + "," + temp186 + "\n";
        codigo += "=,STACK," + temp186 + "," + temp187 + "\n";
        codigo += "=," + temp187 + ",," + temp184 + "\n";
        codigo += "=," + temp184 + ",," + temp188 + "\n";
        codigo += "=,8,," + temp190 + "// Id = sizecad2\n";
        codigo += "+,p," + temp190 + "," + temp191 + "\n";
        codigo += "=,STACK," + temp191 + "," + temp192 + "\n";
        codigo += "=," + temp192 + ",," + temp189 + "\n";
        codigo += "=," + temp189 + ",," + temp193 + "\n";
        codigo += "// fin acceso\n";
        codigo += "+," + temp188 + "," + temp193 + "," + temp194 + "\n";
        codigo += "// Fin operacion\n";
        codigo += "+,p," + temp182 + "," + temp183 + "\n";
        codigo += "=," + temp183 + "," + temp194 + ",STACK\n";
        codigo += "=,10,," + temp196 + "// Id = encontrado\n";
        codigo += "=," + temp196 + ",," + temp195 + "\n";
        codigo += "=," + temp195 + ",," + temp197 + "\n";
        codigo += "=,1,," + temp199 + "\n";
        codigo += "+,p," + temp197 + "," + temp198 + "\n";
        codigo += "=," + temp198 + "," + temp199 + ",STACK\n";
        codigo += "jmp,,," + label26 + " // Salida if\n";
        codigo += "" + label25 + ":\n"; // Condicion falsa\n";
        codigo += "jmp,,," + label29 + "\n";
        codigo += "" + label26 + ":\n"; // FIN IF\n";
        codigo += "=,5,," + temp201 + "// Id = i\n";
        codigo += "=," + temp201 + ",," + temp200 + "\n";
        codigo += "=," + temp200 + ",," + temp202 + "\n";
        codigo += "=,5,," + temp205 + "// Id = i\n";
        codigo += "+,p," + temp205 + "," + temp206 + "\n";
        codigo += "=,STACK," + temp206 + "," + temp207 + "\n";
        codigo += "=," + temp207 + ",," + temp204 + "\n";
        codigo += "=," + temp204 + ",," + temp208 + "\n";
        codigo += "=,1,," + temp209 + "\n";
        codigo += "+," + temp208 + "," + temp209 + "," + temp210 + "\n";
        codigo += "+,p," + temp202 + "," + temp203 + "\n";
        codigo += "=," + temp203 + "," + temp210 + ",STACK\n";
        codigo += "jmp,,," + label20 + "\n";
        codigo += "" + label21 + ":\n";
        codigo += "" + label29 + ":\n"; // Break\n";
        codigo += "jmp,,," + label11 + " // Salida if\n";
        codigo += "" + label10 + ":\n"; // Condicion falsa\n";
        codigo += "" + label11 + ":\n"; // FIN IF\n";
        codigo += "=,3,," + temp212 + "// Id = nuevostring\n";
        codigo += "=," + temp212 + ",," + temp211 + "\n";
        codigo += "=," + temp211 + ",," + temp213 + "\n";
        codigo += "=,3,," + temp216 + "// Id = nuevostring\n";
        codigo += "+,p," + temp216 + "," + temp217 + "\n";
        codigo += "=,STACK," + temp217 + "," + temp218 + "\n";
        codigo += "=," + temp218 + ",," + temp215 + "\n";
        codigo += "=," + temp215 + ",," + temp219 + "\n";
        codigo += "=,1,," + temp221 + "// Id = cad1\n";
        codigo += "+,p," + temp221 + "," + temp222 + "\n";
        codigo += "=,STACK," + temp222 + "," + temp223 + "\n";
        codigo += "=," + temp223 + ",," + temp220 + "\n";
        codigo += "=," + temp220 + ",," + temp224 + "\n";
        codigo += "=,6,," + temp226 + "// Id = j\n";
        codigo += "+,p," + temp226 + "," + temp227 + "\n";
        codigo += "=,STACK," + temp227 + "," + temp228 + "\n";
        codigo += "// Fin identificador\n";
        codigo += "=," + temp228 + ",," + temp225 + "\n";
        codigo += "=," + temp225 + ",," + temp229 + "\n";
        codigo += "// fin acceso\n";
        codigo += "+,p,11,p\n";
        codigo += "+,p,0," + temp230 + "\n";
        codigo += "=," + temp230 + ",-1,STACK\n";
        codigo += "+,p,1," + temp231 + "\n";
        codigo += "=," + temp231 + "," + temp224 + ",STACK\n";
        codigo += "+,p,2," + temp232 + "\n";
        codigo += "=," + temp232 + "," + temp229 + ",STACK\n";
        codigo += "call,,,CharAt_primitiva\n";
        codigo += "+,p,0," + temp233 + "\n";
        codigo += "=,STACK," + temp233 + "," + temp234 + "\n";
        codigo += "-,p,11,p\n";
        codigo += "+,p,11," + temp235 + "\n";
        codigo += "+," + temp235 + ",1," + temp236 + "\n";
        codigo += "=," + temp236 + "," + temp219 + ",STACK\n";
        codigo += "+," + temp235 + ",2," + temp237 + "\n";
        codigo += "=," + temp237 + "," + temp234 + ",STACK\n";
        codigo += "+,p,11,p\n";
        codigo += "call,,,concatenar_Stringchar\n";
        codigo += "+,p,0," + temp238 + "\n";
        codigo += "=,STACK," + temp238 + "," + temp239 + "\n";
        codigo += "-,p,11,p\n";
        codigo += "+,p," + temp213 + "," + temp214 + "\n";
        codigo += "=," + temp214 + "," + temp239 + ",STACK\n";
        codigo += "=,6,," + temp241 + "// Id = j\n";
        codigo += "=," + temp241 + ",," + temp240 + "\n";
        codigo += "=," + temp240 + ",," + temp242 + "\n";
        codigo += "=,6,," + temp245 + "// Id = j\n";
        codigo += "+,p," + temp245 + "," + temp246 + "\n";
        codigo += "=,STACK," + temp246 + "," + temp247 + "\n";
        codigo += "=," + temp247 + ",," + temp244 + "\n";
        codigo += "=," + temp244 + ",," + temp248 + "\n";
        codigo += "=,1,," + temp249 + "\n";
        codigo += "+," + temp248 + "," + temp249 + "," + temp250 + "\n";
        codigo += "+,p," + temp242 + "," + temp243 + "\n";
        codigo += "=," + temp243 + "," + temp250 + ",STACK\n";
        codigo += "jmp,,," + label5 + "\n";
        codigo += "" + label6 + ":\n";
        codigo += "=,0,," + temp252 + "// Id = reemplazar\n";
        codigo += "=," + temp252 + ",," + temp251 + "\n";
        codigo += "=," + temp251 + ",," + temp253 + "\n";
        codigo += "=,3,," + temp256 + "// Id = nuevostring\n";
        codigo += "+,p," + temp256 + "," + temp257 + "\n";
        codigo += "=,STACK," + temp257 + "," + temp258 + "\n";
        codigo += "=," + temp258 + ",," + temp255 + "\n";
        codigo += "=," + temp255 + ",," + temp259 + "\n";
        codigo += "+,p," + temp253 + "," + temp254 + "\n";
        codigo += "=," + temp254 + "," + temp259 + ",STACK\n";
        codigo += "jmp,,," + label30 + "\n";
        codigo += "jmp,,," + label2 + " // Salida if\n";
        codigo += "" + label1 + ":\n"; // Condicion falsa\n";
        codigo += "=,0,," + temp261 + "// Id = reemplazar\n";
        codigo += "=," + temp261 + ",," + temp260 + "\n";
        codigo += "=," + temp260 + ",," + temp262 + "\n";
        codigo += "=,1,," + temp265 + "// Id = cad1\n";
        codigo += "+,p," + temp265 + "," + temp266 + "\n";
        codigo += "=,STACK," + temp266 + "," + temp267 + "\n";
        codigo += "=," + temp267 + ",," + temp264 + "\n";
        codigo += "=," + temp264 + ",," + temp268 + "\n";
        codigo += "// fin acceso\n";
        codigo += "+,p," + temp262 + "," + temp263 + "\n";
        codigo += "=," + temp263 + "," + temp268 + ",STACK\n";
        codigo += "// Fin asignacion\n";
        codigo += "jmp,,," + label31 + "\n";
        codigo += "" + label2 + ":\n"; // FIN IF\n";
        codigo += "" + label30 + ":\n"; // Exi"+temp\n";
        codigo += "" + label31 + ":\n"; // Exi"+temp\n";
        codigo += "end,,,reemplazar_primitiva\n";
        return codigo;
    }

    public String generarIndexOut(Tabla tabla) {
        String codigo = "";
        codigo += "begin,,,indexOutException_primitiva\n";
        codigo += "print(%c,73)\n";
        codigo += "print(%c,110)\n";
        codigo += "print(%c,100)\n";
        codigo += "print(%c,105)\n";
        codigo += "print(%c,99)\n";
        codigo += "print(%c,101)\n";
        codigo += "print(%c,32)\n";
        codigo += "print(%c,102)\n";
        codigo += "print(%c,117)\n";
        codigo += "print(%c,101)\n";
        codigo += "print(%c,114)\n";
        codigo += "print(%c,97)\n";
        codigo += "print(%c,32)\n";
        codigo += "print(%c,100)\n";
        codigo += "print(%c,101)\n";
        codigo += "print(%c,32)\n";
        codigo += "print(%c,114)\n";
        codigo += "print(%c,97)\n";
        codigo += "print(%c,110)\n";
        codigo += "print(%c,103)\n";
        codigo += "print(%c,111)\n";
        codigo += "print(%c,46)\n";
        codigo += "print(%c,10)\n";
        codigo += "end,,,indexOutException_primitiva\n";
        return codigo;
    }

    public String generarRangoFueraLimites(Tabla tabla) {
        String codigo = "";
        codigo += "begin,,,rango_sobrepasado\n";
        codigo += "print(%c,86)\n";
        codigo += "print(%c,97)\n";
        codigo += "print(%c,108)\n";
        codigo += "print(%c,111)\n";
        codigo += "print(%c,114)\n";
        codigo += "print(%c,32)\n";
        codigo += "print(%c,102)\n";
        codigo += "print(%c,117)\n";
        codigo += "print(%c,101)\n";
        codigo += "print(%c,114)\n";
        codigo += "print(%c,97)\n";
        codigo += "print(%c,32)\n";
        codigo += "print(%c,100)\n";
        codigo += "print(%c,101)\n";
        codigo += "print(%c,32)\n";
        codigo += "print(%c,108)\n";
        codigo += "print(%c,111)\n";
        codigo += "print(%c,115)\n";
        codigo += "print(%c,32)\n";
        codigo += "print(%c,108)\n";
        codigo += "print(%c,105)\n";
        codigo += "print(%c,109)\n";
        codigo += "print(%c,105)\n";
        codigo += "print(%c,116)\n";
        codigo += "print(%c,101)\n";
        codigo += "print(%c,115)\n";
        codigo += "print(%c,32)\n";
        codigo += "print(%c,100)\n";
        codigo += "print(%c,101)\n";
        codigo += "print(%c,108)\n";
        codigo += "print(%c,32)\n";
        codigo += "print(%c,114)\n";
        codigo += "print(%c,97)\n";
        codigo += "print(%c,110)\n";
        codigo += "print(%c,103)\n";
        codigo += "print(%c,111)\n";
        codigo += "print(%c,46)\n";
        codigo += "print(%c,10)\n";
        codigo += "end,,,rango_sobrepasado\n";
        return codigo;
    }
}
//86 97 108 111 114 32 102 117 101 114 97 32 100 101 32 108 111 115 32 108 105 109 105 116 101 115 32 100 101 108 32 114 97 110 103 111 46
